services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: xyvex_user
      POSTGRES_PASSWORD: xyvex_password
      POSTGRES_DB: xyvex_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: